### ISSUE TITLE
Feature: Integrate with Initial Inventory

### ISSUE THREAD

**Issue by Timiryazev** [SmashingModsTogether/Reroll#3]
https://www.curseforge.com/minecraft/mc-mods/initial-inventory

If Initial Inventory is loaded, Reroll should have the option to override the "Reroll gear" with the Initial Inventory settings.

**Comment by Dark-Arcana** [comment]
Initial Inventory is an addon for CraftTweaker. Adding CraftTweaker support is very simple and straight forward. However, something must have changed in the last 5 years, because it doesn't load in a development environment and there is no documentation for mods this old.

So instead, I added functionality to set the reroll inventory as a starting inventory with a config option.

Done in c50acaa9a53ebbaa4f7a9af43c99967cdc07ab15
